### ISSUE TITLE
`pop up contract`: build contract if it has not been built

### ISSUE THREAD

**Issue by brunopgalvao** [r0gue-io/pop-cli#34]
Based on this PR comment: https://github.com/r0gue-io/pop-cli/pull/27#discussion_r1515973155

For `pop up contract`, we should do a check, if the contract has not been built, then build it.

**Comment by bolajahmad** [comment]
Hi, I would like to work on this but I need more information. It makes sense to make sure contract is already build before deploying with `pop up`.

How would the `pol-cli` know that the user's project has been built or not? I assume we might have to check for the presence of the `target` directory or similar?

**Comment by AlexD10S** [comment]
Hi! thanks for the interest @bolajahmad. Exactly, after the build a target folder is generated with a`parachain-template-node` binary in it.
This is what we have to check it exists:` target/release/parachain-template-node` and if not call the `build_parachain` method: https://github.com/r0gue-io/pop-cli/blob/main/crates/pop-parachains/src/build.rs#L5 before actually run the pop up parachain logic

**Comment by bolajahmad** [comment]
Thank you @AlexD10S, that I understand.

One side note, this issue is specific about `pop up contract` which is for deploying smart contracts. Your comment seems to be focusing on parachain deployment and got me thinking the `target/realease/parachain-node-template` might be referring to the build of a parachain. 

Correct me if I'm wrong but, to check if a Contract build exists, we should not be checking the same path as the parachain but something like `target/release/ink`.

Also, even though this issue is specifically about `pop up contract`, should I create a commit for the same logic related to the `pop up parachain` too?

**Comment by AlexD10S** [comment]
Sorry I got confused there. I was thinking on the same process but for `pop up parachain` (Which we need too), but you are right this issue is specific for `pop up contract`.
Exactly you are right, this is the ink folder we have to check`target/release/ink` and this is the method to call to build a contract: https://github.com/r0gue-io/pop-cli/blob/main/crates/pop-contracts/src/build.rs#L7
